spring:
  datasource:
    url: jdbc:mysql://db.bank.orb.local:3306/bank?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update

oauth2:
  providers:
    google:
      client-id: sample
      client-secret: sample
      redirect-uri: sample
    github:
      client-id: sample
      client-secret: sample
      redirect-uri: sample

jwt:
  secret-key: asdfasfdasdfadfasdfasdfafdasfasdfafasfasfasfdasfd
  time: 1000
