oauth2:
  providers:
    google:
      client-id: sample
      client-secret: sample
      redirect-uri: sample
    github:
      client-id: sample
      client-secret: sample
      redirect-uri: sample

jwt:
  secret-key: asdfasfdasdfadfasdfasdfafdasfasdfafasfasfasfdasfd
  time: 30

database:
  mysql:
    url: jdbc:mysql://db.bank.orb.local:3306/bank?serverTimezone=UTC
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
